spring.application.name=tp-spring
spring.datasource.url=jdbc:mysql://localhost:3306/tp_spring
spring.datasource.username=root
spring.datasource.password=
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update